### PR TITLE
Transaction finish lock fixes

### LINKED ISSUE #1004: Transaction commit in program halt is not re-entrant
If the `Program::halt()` function returns I/O status code, we attempt to commit a transaction that has already been committed as we retry the instruction. Part of the problem is that we perform checkpointing for every transaction, which is not what we want.

### PR DESCRIPTION
**Pull request by pereman2**
While adding logs to our locks in `Wal` I noticed we weren't cleaning up connection's transaction state. This PR set to `TransactionState::None` once commited and calls `end_read_txn` and `end_tx` in case of write.

Fixes #1004

### CODE REVIEW

File: core/vdbe/mod.rs [hunk 1]
```diff
@@ -3086,22 +3085,26 @@ impl Program {
         tracing::trace!("Halt auto_commit {}", auto_commit);
         if auto_commit {
             let current_state = connection.transaction_state.borrow().clone();
-            if current_state == TransactionState::Read {
+            if matches!(
+                current_state,
+                TransactionState::Read | TransactionState::Write
+            ) {
                 pager.end_read_tx()?;
```
Comment (jussisaurio) [inline core/vdbe/mod.rs:3092]: Quick drive-by comment: does it not matter that `pager.end_read_tx()` might be called multiple times for `TransactionState::Write` in case of `CheckpointStatus::IO`?

Comment (pereman2) [reply core/vdbe/mod.rs:3092]: Does matter! I guess I didn't pay attention right now. Will fix it

Comment (pereman2) [reply core/vdbe/mod.rs]: Fixed!
