### PR TITLE
Handle all SQLite quoting syntax

### LINKED ISSUE #483: Parse error: Table <table> not found (cli interactive)
I created a test db and wanted to open it with `limbo` (interactive cli) using the query `select * from home;`.
This results in the following error message:

> Parse error: Table home not found

The same db and table can be opened just fine with `sqlite3`.
The file in question: 
[home.db.zip](https://github.com/user-attachments/files/18140136/home.db.zip)

Is this related to an unimplemented feature?

### LINKED ISSUE #497: Quoting identifiers
While working on #492 I realized that there are a lot of unhandled AST nodes where `normalize_ident` must be applied and currently isn't. Examples:

```
limbo> select id from users order by "id" limit 1;
Parse error: Column "id" not found
limbo> select id from users order by "users".id limit 1;
Parse error: Table "users" not found
limbo> select id from users order by users.id limit 1;
limbo> select users.id from users where "id" between 1 and 10 limit 1;
Parse error: Column "id" not found
```

We had a brief chat on whether we should hack on the vendored AST or not and the initial suggestion from @jussisaurio was not to:

https://github.com/tursodatabase/limbo/pull/492#issuecomment-2546097250

However, having to call `normalize_ident` everywhere might be a good reason to change it there. I'm not aware of any potential downsides though as I'm not very familiar with the codebase.

It seems that sqlite might be normalizing the quoted names in the AST parser too though: (the error shows unquoted column name)

```
sqlite> select `asd` from users;
Parse error: no such column: asd
  select `asd` from users;
         ^--- error here
sqlite> select [asd] from users;
Parse error: no such column: asd
  select [asd] from users;
         ^--- error here
sqlite> select users."asd" from users;
Parse error: no such column: users.asd
  select users."asd" from users;
         ^--- error here
```

### PR DESCRIPTION
**Pull request by madejejej**
This PR adds missing SQLite quoting syntax: https://sqlite.org/lang_keywords.html

Closes #483 
Closes #497 

```bash
➜  limbo git:(missing-quoting) ✗ cargo run --package limbo --bin limbo home.db
Limbo v0.0.9
Enter ".help" for usage hints.
limbo> select * from home limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
limbo> select * from [home] limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
limbo> select * from `home` limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
limbo> select * from "home" limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
```

### CODE REVIEW

**Comment by penberg** [comment]
Please bring back `rust-toolchain.toml` that was accidentally deleted

**Comment by madejejej** [comment]
ah 🤦 

I deleted it because I was getting this error:

```
➜  limbo git:(missing-quoting) ✗ cargo run --package limbo --bin limbo home.db
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.83.0-aarch64-apple-darwin' toolchain
```

forgot to bring it back.


Also, I'm wondering if it makes more sense to handle the quoting when parsing the AST here?:

https://github.com/tursodatabase/limbo/blob/a03749be213228c597027f028a22cfa49396eeb7/vendored/sqlite3-parser/src/parser/ast/mod.rs#L1002

**Comment by jussisaurio** [comment]
> error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.83.0-aarch64-apple-darwin' toolchain

FYI you can resolve this with

```
rustup component remove cargo
rustup component add cargo
```

**Comment by jussisaurio** [comment]
Can you add a couple of TCL tests in one of the `*.test` files like

```
sqlite> select [first_name] from [users] where [id] = 1 limit 1;
Jamie
```

**Comment by jussisaurio** [comment]
> Also, I'm wondering if it makes more sense to handle the quoting when parsing the AST here?:

I think let's limit hacking the vendored AST unless theres a very good reason for it, we can always take more ownership of that module later if we want. `normalize_ident()` is a decent place to do it IMO

File: core/translate/planner.rs [hunk 1]
```diff
@@ -97,12 +97,13 @@ fn bind_column_references(
                 return Ok(());
             }
             let mut match_result = None;
+            let normalized_id = normalize_ident(id.0.as_str());
```
Comment (madejejej) [inline core/translate/planner.rs:100]: I've also found a few bugs in the previous implementation. This did not work:

```
limbo> select users.id from "users";
Parse error: Table users not found
```

because we didn't normalize the table names and the column names. Do you guys want this to go in a separate PR or can we keep it here?

Comment (madejejej) [reply core/translate/planner.rs:100]: Hmm, this issue is more common:

```
limbo> select users.id from users where "id" between 1 and 10 limit 1;
Parse error: Column "id" not found
```

If we don't normalize the name in the vendored AST, we have to keep in mind it has to be normalized everywhere it's being used.

Comment (madejejej) [reply core/translate/planner.rs:100]: Another one:

```
limbo> select id from users order by "id" limit 1;
Parse error: Column "id" not found
```

**Comment by madejejej** [comment]
I opened #497 to discuss how to solve quoting

**Comment by madejejej** [comment]
Closes #497 

@jussisaurio ready for review :)

File: core/translate/planner.rs [hunk 2]
```diff
@@ -504,8 +508,9 @@ fn parse_from(
 
     let first_table = match *from.select.unwrap() {
         ast::SelectTable::Table(qualified_name, maybe_alias, _) => {
-            let Some(table) = schema.get_table(&qualified_name.name.0) else {
-                crate::bail_parse_error!("Table {} not found", qualified_name.name.0);
+            let normalized_qualified_name = normalize_ident(qualified_name.name.0.as_str());
+            let Some(table) = schema.get_table(&normalized_qualified_name) else {
```
Comment (jussisaurio) [inline core/translate/planner.rs:512]: this is also needed in `parse_join()` right?

Comment (madejejej) [reply core/translate/planner.rs:512]: Good catch. Handled it there + added a test.
