### PR TITLE
Fix bound parameters on insert statements with out of order column indexes

### LINKED ISSUE #1449: INSERT statements seem to ignore column order specification when inserted via Go/Rust/Python adapter
When using named columns in INSERT statements, Limbo seems to be ignoring the specified column order and inserting values according to the table's definition order instead.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/tursodatabase/limbo"
)

func main() {
	fmt.Println("Testing column ordering in INSERT statements")
	fmt.Println("==========================================")

	// Connect to in-memory database
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		log.Fatalf("Failed to open database: %v", err)
	}
	defer db.Close()

	// Create a table with specific column order
	createSQL := `CREATE TABLE IF NOT EXISTS test (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		col_a TEXT,
		col_b TEXT,
		col_c TEXT,
		col_d TEXT);`
	
	_, err = db.Exec(createSQL)
	if err != nil {
		log.Fatalf("Failed to create table: %v", err)
	}

	// Insert data with different column order than table definition
	// Table order: col_a, col_b, col_c, col_d
	// Insert order: col_b, col_d, col_a, col_c
	insertSQL := `INSERT INTO test (col_b, col_d, col_a, col_c) VALUES (?, ?, ?, ?)`
	
	values := []string{"VALUE_B", "VALUE_D", "VALUE_A", "VALUE_C"}
	_, err = db.Exec(insertSQL, values[0], values[1], values[2], values[3])
	if err != nil {
		log.Fatalf("Failed to insert: %v", err)
	}

	// Query data back
	rows, err := db.Query("SELECT id, col_a, col_b, col_c, col_d FROM test")
	if err != nil {
		log.Fatalf("Failed to query: %v", err)
	}
	defer rows.Close()

	fmt.Println("\nColumn Order Expected:")
	fmt.Println("col_a: VALUE_A")
	fmt.Println("col_b: VALUE_B")
	fmt.Println("col_c: VALUE_C")
	fmt.Println("col_d: VALUE_D")

	fmt.Println("\nActual Results:")
	for rows.Next() {
		var id int
		var colA, colB, colC, colD string
		err = rows.Scan(&id, &colA, &colB, &colC, &colD)
		if err != nil {
			log.Fatalf("Failed to scan: %v", err)
		}
		fmt.Printf("id: %d\n", id)
		fmt.Printf("col_a: %s\n", colA)
		fmt.Printf("col_b: %s\n", colB)
		fmt.Printf("col_c: %s\n", colC)
		fmt.Printf("col_d: %s\n", colD)
	}

	// Also test with a different scenario
	fmt.Println("\n\nTest 2: More complex ordering")
	fmt.Println("-----------------------------")

	// Insert with another different order
	_, err = db.Exec(`INSERT INTO test (col_d, col_a, col_c, col_b) VALUES (?, ?, ?, ?)`, 
		"VALUE_D2", "VALUE_A2", "VALUE_C2", "VALUE_B2")
	if err != nil {
		log.Fatalf("Failed to insert test 2: %v", err)
	}

	// Query all data
	rows2, err := db.Query("SELECT id, col_a, col_b, col_c, col_d FROM test ORDER BY id")
	if err != nil {
		log.Fatalf("Failed to query test 2: %v", err)
	}
	defer rows2.Close()

	fmt.Println("\nAll rows:")
	for rows2.Next() {
		var id int
		var colA, colB, colC, colD string
		err = rows2.Scan(&id, &colA, &colB, &colC, &colD)
		if err != nil {
			log.Fatalf("Failed to scan test 2: %v", err)
		}
		fmt.Printf("Row %d: A=%s, B=%s, C=%s, D=%s\n", id, colA, colB, colC, colD)
	}
}
```
```
Testing column ordering in INSERT statements
==========================================

Column Order Expected:
col_a: VALUE_A
col_b: VALUE_B
col_c: VALUE_C
col_d: VALUE_D

Actual Results:
id: 1
col_a: VALUE_B
col_b: VALUE_D
col_c: VALUE_A
col_d: VALUE_C


Test 2: More complex ordering
-----------------------------

All rows:
Row 1: A=VALUE_B, B=VALUE_D, C=VALUE_A, D=VALUE_C
Row 2: A=VALUE_D2, B=VALUE_A2, C=VALUE_C2, D=VALUE_B2
```

### PR DESCRIPTION
**Pull request by PThorpe92**
closes #1449 

A quick `explain` will show the root of the problem:
image
vs `sqlite3`
image

We process the columns in the order they need to be to create the record, and although we store the index of the value meant to be inserted into that column based on the order they are bound, we still lose the original ordering.

## EDIT: Fixed

image

### Multi-row insert:
image

## Solution:

We just needed to traverse the insert values beforehand and create an array of N integers each representing the index of each `ast::Expr::Variable`: then later on we can lookup the `value_index` in that array, and grab the index of matching integer to get  the parameters index to be bound to the relevant variable.

(yes I know that sounds like a leetcode problem)

Thanks to @jnesss for the write-up for this bug

### CODE REVIEW

**Comment by PThorpe92** [comment]
EDIT: fixed

File: core/parameters.rs [hunk 1]
```diff
@@ -49,6 +54,26 @@ impl Parameters {
         params.len()
     }
 
+    pub fn set_value_index(&mut self, idx: usize) {
```
Comment (jussisaurio) [inline core/parameters.rs:57]: i would personally create some kind of `Option<InsertContext>` struct for `param_positions` and `current_col_value_idx`, move those there, and comment these methods there. i can imagine it will be a bit difficult to understand what these are when reading the code, since parameters aren't otherwise insert-specific, and these methods don't have any documentation.

File: core/translate/expr.rs [hunk 2]
```diff
@@ -2541,6 +2538,16 @@ pub fn maybe_apply_affinity(col_type: Type, target_register: usize, program: &mu
     }
 }
 
+/// Gather all the expected indicies of all Expr::Variable
+pub fn expected_param_indicies(cols: &[Vec<ast::Expr>]) -> Vec<usize> {
```
Comment (jussisaurio) [inline core/translate/expr.rs:2542]: this is a weird place to have this, since this is again insert-specific and it's in `expr.rs` with no mention that it relates to insert logic

**Review by jussisaurio — APPROVED** [review]
Fix looks good but I'd really prefer some additional effort to documentation

File: core/parameters.rs (hunk 1 above)
Comment (PThorpe92) [reply core/parameters.rs:57]: Yeah you are absolutely right. The first fix I had outlined here I had loads of documentation (mostly because it was totally convoluted), but I didn't go back and add any back when I changed the approach.

File: core/translate/expr.rs (hunk 2 above)
Comment (PThorpe92) [reply core/translate/expr.rs]: Yeah this was also a left over from the first fix. I pushed some changes that really simplifies the API with your suggestions and adds some docs.

**Comment by PThorpe92** [comment]
Docs and suggestions added :+1:
