### PR TITLE
cli: Add newline characters on multiline prompts

### LINKED ISSUE #980: Processing JSON from stdin is broken
If I run the following JSON test in interactive mode, it works:

```
limbo % cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/limbo`
Limbo v0.0.14
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database
limbo> SELECT json(' /* abc */ { /*def*/ aaa /* xyz */ : // to the end of line
          123 /* xyz */ , /* 123 */ }');
{"aaa":123}
```

However, if I try to run the same JSON query through stdin, Limbo complains about malformed JSON:

```
limbo % cat input-json.txt
SELECT json(' /* abc */ { /*def*/ aaa /* xyz */ : // to the end of line
          123 /* xyz */ , /* 123 */ }')
limbo % cat input-json.txt | cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/limbo`
Limbo v0.0.14
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database
Parse error: malformed JSON
```

### PR DESCRIPTION
**Pull request by ploMP4**
Fixes #980

### CODE REVIEW

File: cli/app.rs [hunk 1]
```diff
@@ -502,7 +502,7 @@ impl Limbo {
             }
             self.reset_input();
         } else {
-            self.buffer_input(line);
+            self.buffer_input(format!("{}\n", line).as_str());
```
Comment (ihorandrianov) [inline cli/app.rs:505]: Hello! There is no need in cloning line, just add "\n" to buffer_input.

**Comment by penberg** [comment]
Hey @ploMP4, I am not sure I understand _why_ does this fix the problem?

**Comment by ihorandrianov** [comment]
Rustyline in non terminal mode reads input like a file content line by line splitting by '\n'  in json where we care about new lines actually.  Also lines trimmed here, removing \n
```rust
match readline {
            Ok(line) => match app.handle_input_line(line.trim(), &mut rl) {
                Ok(_) => {}
                Err(e) => {
                    eprintln!("{}", e);
                }
            }
```

File: cli/app.rs (hunk 1 above)
Comment (ploMP4) [reply cli/app.rs:505]: Hi! thanks for the comment, but after giving it a second thought i think that the "\n" should just go into the `buffer_input` function because right now it adds a whitespace after the line meaning if you try to run something like like `echo "SELECT 'foo\nbar'" | cargo run` you'll get

```
foo
 bar
 ```

whereas `echo "SELECT 'foo\nbar" | sqlite3` gives you

```
foo
bar
```

**Comment by ploMP4** [comment]
> Hey @ploMP4, I am not sure I understand _why_ does this fix the problem?

Hi @penberg! I think @ihorandrianov explained it well. Essentially, in the example provided in the issue, the file input is being parsed as a single line instead of multiple lines. Because of that, the comment at the end of the first line ends up cutting off the second line as well.
