### PR TITLE
Fix WAL frame checksum mismatch

### LINKED ISSUE #1622: WAL frame checksum mismatch
Limbo crashes for me locally if shell will be restarted WAL is big enough:

```
$> limbo --version
limbo 0.0.21

$> limbo a.db
limbo> CREATE TABLE t(x);
limbo> INSERT INTO t VALUES (randomblob(512 * 1024)); 
limbo> INSERT INTO t SELECT * FROM t;
limbo> INSERT INTO t SELECT * FROM t;
limbo> INSERT INTO t SELECT * FROM t;
limbo> INSERT INTO t SELECT * FROM t;
limbo> ^C
Interrupted. Exiting...

$> limbo a.db
thread 'main' panicked at core/storage/sqlite3_ondisk.rs:1495:17:
WAL frame checksum mismatch. Expected (3480643840, 2904012637), Got (4135411069, 2138363541)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    64670 IOT instruction (core dumped)  limbo a.db
```

### PR DESCRIPTION
**Pull request by el-yawd**
Closes #1622

I did an A/B test between SQLite and Limbo and they can restart the db from each other, indicating that there isn't something very wrong with our file format. Turns out it was with our reset logic without truncating the file. I assumed it's safe to don't reset if we're in `PASSIVE` mode, given the [docs](https://www.sqlite.org/c3ref/wal_checkpoint_v2.html) and [source code](https://github.com/sqlite/sqlite/blob/2bd9f69d40dd240c4122c6d02f1ff447e7b5c098/src/wal.c#L2193).

It also does some small clean ups and fixes.

### CODE REVIEW

File: core/storage/sqlite3_ondisk.rs [hunk 1]
```diff
@@ -1471,11 +1471,16 @@ pub fn read_entire_wal_dumb(file: &Arc<dyn File>) -> Result<Arc<UnsafeCell<WalFi
             let frame_h_checksum_2 =
                 u32::from_be_bytes(frame_header_slice[20..24].try_into().unwrap());
 
+            // It contains more frames with mismatched SALT values, which means they're leftovers from previous checkpoints
```
Comment (el-yawd) [inline core/storage/sqlite3_ondisk.rs:1476]: [Source](https://github.com/psarna/wal-browser/blob/4fbe9f1870b6d73771d3de0a4982846e87e7b917/src/main.rs#L122), it also matches with documentation

**Comment by jussisaurio** [comment]
should this PR also make our checkpoint use a different salt for each checkpoint, since the WalHeader struct now contains this documentation?

/// Random value used for the first salt in checksum calculations, incremented with each checkpoint
/// Random value used for the second salt in checksum calculations. A different random value for each checkpoint

i don't think we do either of these things? can also be marked with TODO if done in separate PR, but we shouldn't just leave the documentation like this if it isn't true

cc @pereman2 

https://github.com/tursodatabase/limbo/issues/1649
https://github.com/tursodatabase/limbo/issues/1650

File: core/storage/wal.rs [hunk 2]
```diff
@@ -767,7 +772,7 @@ impl Wal for WalFile {
                     };
                     let everything_backfilled = shared.max_frame.load(Ordering::SeqCst)
                         == self.ongoing_checkpoint.max_frame;
-                    if everything_backfilled {
+                    if everything_backfilled && !matches!(mode, CheckpointMode::Passive) {
```
Comment (jussisaurio) [inline core/storage/wal.rs]: We only use `CheckpointMode::Passive` so the reseting is effectively dead code for the time being, right? The proper way would be to check whether there are any transactions using the WAL, as this earlier comment says:

`// TODO(pere): check what frames are safe to checkpoint between many readers!`

With this change we just keep growing the WAL file indefinitely, correct?

Comment (el-yawd) [reply core/storage/wal.rs]: Yep, I tried to do the minimum available change to solve the issue, which is just ignoring the resetting.

> With this change we just keep growing the WAL file indefinitely, correct?

Correct, but for my understanding it's what SQLite does in passive mode, to properly reset we would need restart mode. I can be wrong here, but anyways don't resetting is better than breaking.

**Comment by el-yawd** [comment]
> should this PR also make our checkpoint use a different salt for each checkpoint, since the WalHeader struct now contains this documentation?
> 
> /// Random value used for the first salt in checksum calculations, incremented with each checkpoint /// Random value used for the second salt in checksum calculations. A different random value for each checkpoint
> 
> i don't think we do either of these things? can also be marked with TODO if done in separate PR, but we shouldn't just leave the documentation like this if it isn't true
> 
> cc @pereman2
> 
> #1649 #1650

Agree, I think marking as a TODO is better, I'll work on this other PR ASAP

File: core/storage/wal.rs (hunk 2 above)
Comment (jussisaurio) [reply core/storage/wal.rs]: :+1: Can you also comment this above that line with a TODO, and open an issue if one doesnt exist yet?

Comment (el-yawd) [reply core/storage/wal.rs]: Aye aye captain

File: core/storage/wal.rs [hunk 3]
```diff
@@ -772,13 +772,18 @@ impl Wal for WalFile {
                     };
                     let everything_backfilled = shared.max_frame.load(Ordering::SeqCst)
                         == self.ongoing_checkpoint.max_frame;
+
+                    // It's what SQLite does in passive mode, to properly reset we would need restart mode.
```
Comment (jussisaurio) [inline core/storage/wal.rs]: I find it hard to believe PASSIVE checkpoint mode lets the WAL keep growing indefinitely. Do you have a specific source line or section for this?

Also, 

> It's what SQLite does in passive mode

What is "it's"? The comment should say it

Comment (el-yawd) [reply core/storage/wal.rs]: Yep, in [walCheckpoint](https://github.com/sqlite/sqlite/blob/2bd9f69d40dd240c4122c6d02f1ff447e7b5c098/src/wal.c#L2193), to truncate **the wal file** it must held a writer lock which isn't possible in passive mode. Also note that when it does modify the wal header, it first checks if it isn't in passive mode:

```C

  /* If this is an SQLITE_CHECKPOINT_RESTART or TRUNCATE operation, and the
  ** entire wal file has been copied into the database file, then block
  ** until all readers have finished using the wal file. This ensures that
  ** the next process to write to the database restarts the wal file.
  */
  if( rc==SQLITE_OK && eMode!=SQLITE_CHECKPOINT_PASSIVE ){ // <------- Ensure it isn't in passive mode
    assert( pWal->writeLock );
    SEH_INJECT_FAULT;
    if( pInfo->nBackfill<pWal->hdr.mxFrame ){
      rc = SQLITE_BUSY;
    }else if( eMode>=SQLITE_CHECKPOINT_RESTART ){
      u32 salt1;
      sqlite3_randomness(4, &salt1);
      assert( pInfo->nBackfill==pWal->hdr.mxFrame );
      rc = walBusyLock(pWal, xBusy, pBusyArg, WAL_READ_LOCK(1), WAL_NREADER-1);
      if( rc==SQLITE_OK ){
        if( eMode==SQLITE_CHECKPOINT_TRUNCATE ){
          /* IMPLEMENTATION-OF: R-44699-57140 This mode works the same way as
          ** SQLITE_CHECKPOINT_RESTART with the addition that it also
          ** truncates the log file to zero bytes just prior to a
          ** successful return.
          **
          ** In theory, it might be safe to do this without updating the
          ** wal-index header in shared memory, as all subsequent reader or
          ** writer clients should see that the entire log file has been
          ** checkpointed and behave accordingly. This seems unsafe though,
          ** as it would leave the system in a state where the contents of
          ** the wal-index header do not match the contents of the
          ** file-system. To avoid this, update the wal-index header to
          ** indicate that the log file contains zero valid frames.  */
          walRestartHdr(pWal, salt1); // <----------- Restart the header
          rc = sqlite3OsTruncate(pWal->pWalFd, 0); // <------ AND truncate the wal file
        }
        walUnlockExclusive(pWal, WAL_READ_LOCK(1), WAL_NREADER-1);
      }
    }
```

What tricked me was that SQLite can do truncate if in passive mode, but on the db file:

```C

  /* If work was actually accomplished... */
      if( rc==SQLITE_OK ){
        if( mxSafeFrame==walIndexHdr(pWal)->mxFrame ){
          i64 szDb = pWal->hdr.nPage*(i64)szPage;
          testcase( IS_BIG_INT(szDb) );
          rc = sqlite3OsTruncate(pWal->pDbFd, szDb); // <---- pWal->pDbFd is the file handle for the database file
          if( rc==SQLITE_OK ){
            rc = sqlite3OsSync(pWal->pDbFd, CKPT_SYNC_FLAGS(sync_flags)); 
          }
        }
        if( rc==SQLITE_OK ){
          AtomicStore(&pInfo->nBackfill, mxSafeFrame); SEH_INJECT_FAULT;
        }
      }

      /* Release the reader lock held while backfilling */
      walUnlockExclusive(pWal, WAL_READ_LOCK(0), 1);
    }
```

Given that, I'm most convinced that in this mode SQLite lets the WAL grow and defer the task of truncating and resetting the header to other modes.

I'll improve the comments to clarify that.

Comment (jussisaurio) [reply core/storage/wal.rs]: Reset isn't the same as truncate though - reset means you start writing to the beginning of the WAL file, overwriting existing frames, using new WAL header salts for checksumming

But ok, if it doesn't even reset in PASSIVE mode then that's clear

Comment (jussisaurio) [reply core/storage/wal.rs]: For reference here's the `walRestartLog` function in sqlite, which also calls `walRestartHdr`: https://github.com/sqlite/sqlite/blob/master/src/wal.c#L3848

Which is called by `walFrames()` here: https://github.com/sqlite/sqlite/blob/master/src/wal.c#L4052

From a quick glance this looks to me like whenever a new frame is written, sqlite checks whether it can reset the WAL there. So this means in passive mode, the WAL doesnt grow without bound, but an attempt to start overwriting existing frames is made during frame writing, instead of after checkpoint -- so we should eventually have this logic in `fn append_frame()` then
