### PR TITLE
Autoindex fix

### LINKED ISSUE #1508: Create table panic bugs related to constraints
#1494 was merged but contains some bugs:

```sql
limbo> create table t4(a, unique(b));

thread 'main' panicked at core/schema.rs:988:29:
Column b is in index sqlite_autoindex_t4_1 but not found in table t4
```

```sql
limbo> create table t2(a,b, unique(a,b), primary key(a,b));

thread 'main' panicked at core/schema.rs:1012:13:
number of auto_indices in schema should be same number of indices calculated
```

```sql
limbo> create table t4(a,b, primary key(a,b), unique(a));

thread 'main' panicked at core/schema.rs:981:71:
number of auto_indices in schema should be same number of indices calculated
```

### PR DESCRIPTION
**Pull request by pedrocarlo**
Closes #1508 . There were two small issues to fix:

1. We were not checking in the IndexMap of columns, if the unique column name is declared in the composite declaration exists in the IndexMap. This solved the first this statement `create table t4(a, unique(b));`.
2. The second thing was that we forgot to add the column_name to the HashSet of columns. 
```rust
Some(PrimaryKeyDefinitionType::Simple { column, .. }) => {
      let mut columns = HashSet::new();
      columns.insert(std::mem::take(column));
      // Have to also insert the current column_name we are iterating over in primary_key_column_results
      columns.insert(column_name.clone()); <-- Fix here
      primary_key_definition =
           Some(PrimaryKeyDefinitionType::Composite { columns });
      }
```
The rest of the modifications are just some small simplifications for readability and avoiding some clones

### CODE REVIEW

File: core/translate/schema.rs [hunk 1]
```diff
@@ -288,44 +289,47 @@ fn check_automatic_pk_index_required(
...
-                        let primary_key_column_results: Vec<Result<PrimaryKeyColumnInfo>> = pk_cols
+                        let primary_key_column_results = pk_cols
                             .iter()
                             .map(|col| match &col.expr {
-                                ast::Expr::Id(name) => Ok(PrimaryKeyColumnInfo {
-                                    name: &name.0,
-                                    is_descending: matches!(col.order, Some(ast::SortOrder::Desc)),
-                                }),
+                                ast::Expr::Id(name) => {
+                                    let key: &ast::Name = unsafe { std::mem::transmute(name) };
```
Comment (jussisaurio) [inline core/translate/schema.rs:296]:
```rust
                                    if !columns.iter().any(|(k, _)| k.0 == name.0) {
                                        bail_parse_error!("No such column: {}", name.0);
                                    }
```

?

File: core/translate/schema.rs [hunk 2]
```diff
@@ -288,44 +289,47 @@ fn check_automatic_pk_index_required(
...
+                            .collect::<Result<Vec<_>>>()?;
 
+                        for pk_info in primary_key_column_results {
                             let column_name = pk_info.name;
-                            let column_def = columns.get(&ast::Name(column_name.clone()));
-                            if column_def.is_none() {
-                                bail_parse_error!("No such column: {}", column_name);
-                            }
+                            let key: &ast::Name = unsafe { std::mem::transmute(column_name) };
+                            let column_def = columns.get(key).unwrap();
```
Comment (jussisaurio) [inline core/translate/schema.rs:318]: same here as above except with `.iter().find().expect()`

File: core/translate/schema.rs [hunk 3]
```diff
@@ -339,24 +343,29 @@ fn check_automatic_pk_index_required(
...
+
+                        let col_names = unique_columns
                             .iter()
                             .map(|column| match &column.expr {
                                 limbo_sqlite3_parser::ast::Expr::Id(id) => {
-                                    crate::util::normalize_ident(&id.0)
+                                    let key: &ast::Name = unsafe { std::mem::transmute(id) };
+                                    if !columns.contains_key(key) {
+                                        crate::bail_parse_error!("no such column: {}", id.0);
+                                    }
```
Comment (pereman2) [inline core/translate/schema.rs:361]: Why is this transmute needed?

**Review by pereman2 — COMMENTED** [review]
Can we have some tests to validate this?

File: core/translate/schema.rs (hunk 3 above)
Comment (jussisaurio) [reply core/translate/schema.rs:361]: because the map is keyed by Name, not Id. but we can avoid it by just iterating the keys

Comment (pedrocarlo) [reply core/translate/schema.rs:361]: Yeah, I did it like to avoid the clone. But, realistically, the number of columns should be small so a linear search should be fine.

File: core/translate/schema.rs (hunk 2 above)
Comment (pedrocarlo) [reply core/translate/schema.rs]: Done

**Review by jussisaurio — APPROVED** [review]
