### PR TITLE
VTabs: Proper handling of re-opened db files without the relevant extensions loaded

### LINKED ISSUE #1239: Cannot open database that has virtual tables created with extensions
If you create a virtual table, for example, with an extension loaded, attempting to open the file again results in this bad error message:

```
limbo % cargo run -- testing.db
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/limbo testing.db`
Limbo v0.0.18
Enter ".help" for usage hints.
limbo> .load target/debug/liblimbo_ext_tests
limbo> create virtual table t using kv_store;
limbo> insert into t values ('hello', 'world');
limbo>
limbo % cargo run -- testing.db
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/limbo testing.db`
thread 'main' panicked at core/util.rs:63:65:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
limbo> .load target/debug/liblimbo_ext_tests
limbo> .open testing.db
thread 'main' panicked at core/util.rs:63:65:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by PThorpe92**
closes #1239 
image

warns the user if a .db file is opened that contains a schema entry of a vtab created with a module that is no longer loaded.

If the module is loaded for that connection, the user can properly query the table.

### CODE REVIEW

File: core/lib.rs [hunk 1]
```diff
@@ -278,9 +284,9 @@ pub struct Connection {
     pager: Rc<Pager>,
     schema: Arc<RwLock<Schema>>,
     header: Arc<SpinLock<DatabaseHeader>>,
-    auto_commit: RefCell<bool>,
+    auto_commit: Cell<bool>,
```
Comment (PThorpe92) [inline core/lib.rs:287]: just realized I applied these changes to a branch I already had open, didn't mean to include irrelevant fixes

File: core/ext/dynamic.rs [hunk 2]
```diff
@@ -44,7 +48,15 @@ impl Connection {
         let result_code = unsafe { entry(api_ptr) };
         if result_code.is_ok() {
             let extensions = get_extension_libraries();
-            extensions.lock().unwrap().push((Arc::new(lib), api_ref));
+            extensions
+                .lock()
+                .map_err(|_| {
+                    LimboError::ExtensionError("Error unlocking extension libraries".to_string())
```
Comment (jussisaurio) [inline core/ext/dynamic.rs:54]: `locking`

**Review by jussisaurio — APPROVED** [review]
