### PR TITLE
core: disk serialization changes to align with sqlite

### LINKED ISSUE #532: creating two tables sometimes corrupts database
```
limbo> create table a (b integer primary key);
limbo> create table b (c integer primary key); <-- doesn't seem to matter what this is
```

```
SQLite version 3.46.0 2024-05-23 13:25:27
Enter ".help" for usage hints.
sqlite> select * from a;
Parse error: malformed database schema (b) - invalid rootpage (11)
```

doesn't happen every time

### PR DESCRIPTION
**Pull request by jussisaurio**
This PR's genesis is from investigating #532, but I still can't reliably reproduce it on either `main` or this branch so I don't know if this PR _fixes_ anything, but I guess it aligns us more with sqlite anyway

---

Anyway: I looked at DBs created with limbo and with sqlite using [ImHex](https://github.com/WerWolv/ImHex) and the differences seem to be:

1. SQLite uses varint according to [the spec](https://www.sqlite.org/fileformat.html#record_format), whereas limbo always encodes integers as i64
2. Limbo adds 4 bytes of zeros for overflow page pointer (even in cases where the cell doesnt overflow)
3. Limbo adds a space after `CREATE TABLE name` before the `(` even when user doesn't specify it?

I implemented the following:

- Fix 1: Varint serialization of i8, i16, i24, i32, i48 and i64 according to payload, instead of always using i64
- Fix 2: Removed the 4 bytes reserved for overflow page pointer in non-overflow cases

### CODE REVIEW

File: core/types.rs [hunk 1]
```diff
@@ -387,39 +387,78 @@ pub struct OwnedRecord {
...
 
         let mut header_size = buf.len() - initial_i;
         // write content
-        for value in &self.values {
-            // TODO: make integers and floats with smaller serial types
+        for (value, &serial_type) in self.values.iter().zip(serial_types.iter()) {
             match value {
                 OwnedValue::Null => {}
-                OwnedValue::Integer(i) => buf.extend_from_slice(&i.to_be_bytes()),
+                OwnedValue::Integer(i) => match serial_type {
```
Comment (jussisaurio) [inline core/types.rs:453]: is it better to just recalculate serial type here instead of allocating a vec above

**Review by pereman2 — APPROVED** [review]
Thanks for this PR! I believe the the problem with create table is not really a problem and I believe it is a problem with how `PRAGMA page_count` works. 

If you do 

```sql
  create table b(b integer primary key);
  create table b2(b integer primary key);
```
in limbo, and then in sqlite:
```
PRAGMA page_count
```
it returns 2 which should be 3 but somehow it is saying we only have 2 pages.
