### PR TITLE
Remove RWLock from Shared wal state

### LINKED ISSUE #780: Performance regression in `SELECT 1`
We have a large performance regression in `SELECT 1`, which looks to have been caused by two different points in time. The first time I can observe a regression is after https://github.com/tursodatabase/limbo/pull/655 merge. I unfortunately am unable to pinpoint the commit as the pull request is not bisectable internally. The regression does get worse over time too, but I did not yet look into it.

### PR DESCRIPTION
**Pull request by pereman2**
Fixes #780

WalShared state can be shared without having to wrap everything with a lock, and instead use atomics on some places and rwlock on others -- for now.

## Results:
From:
----
```
Execute `SELECT 1`/limbo_execute_select_1
                        time:   [34.125 ns 34.218 ns 34.324 ns]
Execute `SELECT 1`/sqlite_execute_select_1
                        time:   [28.124 ns 28.254 ns 28.385 ns]
```

To:
----
```bash
Execute `SELECT 1`/limbo_execute_select_1
                        time:   [31.919 ns 32.113 ns 32.327 ns]
Execute `SELECT 1`/sqlite_execute_select_1
                        time:   [29.662 ns 29.900 ns 30.139 ns]

```
And with `begin_read_tx` inlined:
----

```bash
Execute `SELECT 1`/limbo_execute_select_1
                        time:   [30.543 ns 30.585 ns 30.632 ns]
```

### CODE REVIEW

File: core/storage/wal.rs [hunk 1]
```diff
@@ -360,14 +359,17 @@ impl Wal for WalFile {
...
-            return Ok(LimboResult::Busy);
+        let shared = self.get_shared();
+        {
+            let lock = &mut shared.read_locks[max_read_mark_index as usize];
+            let busy = !lock.read();
+            if busy {
+                return Ok(LimboResult::Busy);
+            }
         }
+        self.min_frame = shared.nbackfills.load(Ordering::SeqCst) + 1;
```
Comment (PThorpe92) [inline core/storage/wal.rs:370]: do we want to have wrapper methods for handling the atomics fields? Since we are always using the same ordering and such
