### PR TITLE
Fix database header initialization

### LINKED ISSUE #1725: DB header and schema should be read from WAL if page 1 is in WAL
Currently limbo just reads these from the DB file and stores it in memory, which causes bugs -- for example, the database size (in pages) may be out of date in the DB file if pages were added to the WAL and page 1 was also modified in the WAL to reflect this.

DB header should be read normally via Pager so that whether page 1 comes from WAL or DB file is invisible to the caller

### LINKED ISSUE #1818: Simulation failure "Freelist: size is 4 but should be 2"
```cargo run -p limbo_sim -- --seed 5977531639967693528```

```ERROR limbo_sim: 171: simulation failed: integrity check failed:
simulation failed: - *** in database main ***
Freelist: size is 4 but should be 2
seed: 5977531639967693528
path: .bugbase/5977531639967693528/
Error: simulation failed: - *** in database main ***
Freelist: size is 4 but should be 2```

### PR DESCRIPTION
**Pull request by el-yawd**
This PR makes limbo read the database header and schema via the regular pager `read_page()` route, instead of always reading it from the database file. This is very important for correctness as modifications to page 1 (containing header and schema) may exist in WAL frames, not just the main database file. Without this, practically any real use of the database would very quickly corrupt the DB as limbo would read the incorrect page count from the stale page 1 copy in the database file, and e.g. allocate the same rootpage for multiple tables and so on.

This issue has been so far hidden due to lack of tests and the fact that `Connection::close()` checkpoints the DB by default, which has delayed discovering this incredibly basic issue since most manual testing has happened via CLI, and if everything is always checkpointed, reopening the DB doesn't cause any problems.

This closes #1725

See also: #1762 (commit from this PR is bundled into this branch as well)

EDIT: Also closes #1818

### CODE REVIEW

File: core/lib.rs [hunk 1]
```diff
@@ -175,22 +159,24 @@ impl Database {
...
-            shared_wal: shared_wal.clone(),
+            maybe_shared_wal: RwLock::new(maybe_shared_wal),
             db_file,
             io: io.clone(),
-            page_size,
             open_flags: flags,
         };
         let db = Arc::new(db);
-        {
+        if db_size > 0 || wal_has_frames {
```
Comment (pereman2) [inline core/lib.rs:181]: I think if `wal_has_frames == true` then `db_size > 0 ` will always be true in theory.

File: core/storage/pager.rs [hunk 2]
```diff
@@ -544,17 +591,25 @@ impl Pager {
...
+        }
         self.wal.borrow_mut().begin_read_tx()
     }
 
     #[inline(always)]
     pub fn begin_write_tx(&self) -> Result<LimboResult> {
+        // We allocate the first page lazily in the first transaction
+        if self.is_empty.load(Ordering::SeqCst) {
+            self.allocate_page1()?;
+        }
```
Comment (pereman2) [inline core/storage/pager.rs]: I think the order is always: 1. `begin_read_tx` 2. `begin_write_tx` in case of write txn anyways, so maybe this is unnecessary.

File: core/storage/pager.rs [hunk 3]
```diff
@@ -265,9 +259,64 @@ impl Pager {
...
+            self.io.run_once()?;
+        }
+        let page_inner = page.get();
+        let page_content = page_inner.contents.as_ref().unwrap();
+        let buf = page_content.buffer.borrow();
+        let buf = buf.as_slice();
+        header.magic.copy_from_slice(&buf[0..16]);
+        header.page_size = u16::from_be_bytes([buf[16], buf[17]]);
+        header.write_version = buf[18];
+        header.read_version = buf[19];
```
Comment (pereman2) [inline core/storage/pager.rs]: Maybe DatabaseHeader could just be a wrapper around an `PageRef` and there you can provide some api to access any part of the header instead of re-initializing everything.

File: core/storage/pager.rs [hunk 4]
```diff
@@ -544,17 +591,25 @@ impl Pager {
...
-        let db_header = self.db_header.lock();
+        let db_header = self.db_header().unwrap();
         (db_header.get_page_size() - db_header.reserved_space as u32) as usize
     }
 
     #[inline(always)]
     pub fn begin_read_tx(&self) -> Result<LimboResult> {
+        // We allocate the first page lazily in the first transaction
+        if self.is_empty.load(Ordering::SeqCst) {
+            self.allocate_page1()?;
```
Comment (pereman2) [inline core/storage/pager.rs]: I think two threads could try to initialize database at the same time so it makes sense for us to have a lock like sqlite (`btreeBeginTrans`):
```c
    /* Call lockBtree() until either pBt->pPage1 is populated or
    ** lockBtree() returns something other than SQLITE_OK. lockBtree()
    ** may return SQLITE_OK but leave pBt->pPage1 set to 0 if after
    ** reading page 1 it discovers that the page-size of the database
    ** file is not pBt->pageSize. In this case lockBtree() will update
    ** pBt->pageSize to the page-size of the file on disk.
    */
    while (pBt->pPage1 == 0 && SQLITE_OK == (rc = lockBtree(pBt)))
      ;

    if (rc == SQLITE_OK && wrflag) {
      if ((pBt->btsFlags & BTS_READ_ONLY) != 0) {
        rc = SQLITE_READONLY;
      } else {
        rc = sqlite3PagerBegin(pPager, wrflag > 1, sqlite3TempInMemory(p->db));
        if (rc == SQLITE_OK) {
          rc = newDatabase(pBt);
        } else if (rc == SQLITE_BUSY_SNAPSHOT &&
                   pBt->inTransaction == TRANS_NONE) {
          /* if there was no transaction opened when this function was
          ** called and SQLITE_BUSY_SNAPSHOT is returned, change the error
          ** code to SQLITE_BUSY. */
          rc = SQLITE_BUSY;
        }
      }
    }

```

File: core/storage/btree.rs [hunk 5]
```diff
@@ -3013,7 +3013,7 @@ impl BTreeCursor {
                     assert_eq!(left_pointer, page.get().get().id as u32);
                     // FIXME: remove this lock
                     assert!(
-                        left_pointer <= self.pager.db_header.lock().database_size,
+                        left_pointer <= self.pager.db_header()?.database_size,
```
Comment (pereman2) [inline core/storage/btree.rs]: Hmmm I don't know about this, if somewhere we decided to evict page 1 from cache then `db_header()` might loop internally until `io` is completed. I wonder if we should follow an approach where we do something like these two options:

1. begin_read_tx: Here we will read page 1 from pager, meaning it might read from wal or not. Then we store the contents of header in `Pager` and since we are sure this transaction will only with database header snapshot we can keep it in memory without worrying about eviction.
2. We treat `db_header` as any other potentially re-entrant code that might need `io.run_once` so this will need to return `IO` in case of not being loaded yet.

Comment (pereman2) [reply core/storage/btree.rs]: It looks like sqlite updates databaes header in its pager shared state between connections:
```c
struct BtShared {
  Pager *pPager;        /* The page cache */
  sqlite3 *db;          /* Database connection currently using this Btree */
  BtCursor *pCursor;    /* A list of all open cursors */
  MemPage *pPage1;      /* First page of the database */

```

File: core/lib.rs (hunk 1 above)
Comment (el-yawd) [reply core/lib.rs:181]: Yes, agree. Idk which issue e94a24f43c52b67a6e89df25a8d7312c3bef9e75 address

Comment (jussisaurio) [reply core/lib.rs:181]: well, currently we dont specialcase page 1 at all, so we can have a situation where db size is 0 and page 1 is in the wal

Comment (jussisaurio) [reply core/lib.rs:181]: hence: unless we do specialcase it and manually checkpoint it when initialized, then you wont be able to find tables you created in a new db if you reopen the db. this is exactly one of those issues that conn.close() autocheckpointing hides.

Comment (jussisaurio) [reply core/lib.rs:181]: so either we implement page1 special logic or wal_has_frames needs to be there. in fact, CI is now failing because that logic was removed.

Comment (el-yawd) [reply core/lib.rs:181]: Yeah, I'll add a comment to makes this explicit

File: core/storage/pager.rs (hunk 2 above)
Comment (el-yawd) [reply core/storage/pager.rs]: Yes, if we start a transaction using `OP_TRANSACTION`, but `OpenEphemeral` needs to start a write txn without emitting this opcode, I think the better way to handle this is implementing something like `sqlite3BtreeBeginTrans`. For now I think it's fine to let this way, I'll open an issue for that.

File: core/storage/pager.rs [hunk 6]
```diff
@@ -551,16 +554,18 @@ impl Pager {
...
+        // Use a loop similar to SQLite's btreeBeginTrans to handle concurrent initialization
+        while self.is_empty.load(Ordering::SeqCst) {
+            let _lock = self.init_lock.lock().unwrap();
             self.allocate_page1()?;
         }
         self.wal.borrow_mut().begin_read_tx()
     }
 
     #[inline(always)]
     pub fn begin_write_tx(&self) -> Result<LimboResult> {
```
Comment (pereman2) [inline core/storage/pager.rs:566]: Wouldn't it be simpler to just move initialization after taking the lock that is implicitly taken in `begin_write_tx`? I think there is no need for this mutex, and furthermore, 2 threads can still call allocate page because one will wait nad once unlocked it will try to allocate it which is wrong.

File: core/vdbe/execute.rs [hunk 7]
```diff
@@ -1680,7 +1680,7 @@ pub fn op_transaction(
         unreachable!("unexpected Insn {:?}", insn)
     };
     let conn = program.connection.clone();
-    if *write && !conn._db.open_flags.contains(OpenFlags::ReadOnly) {
+    if *write && conn._db.open_flags.contains(OpenFlags::ReadOnly) {
```
Comment (pereman2) [inline core/vdbe/execute.rs:1683]: lmao

File: core/lib.rs [hunk 8]
```diff
@@ -202,7 +202,12 @@ impl Database {
 
         // Open existing WAL file if present
         if let Some(shared_wal) = self.maybe_shared_wal.read().clone() {
-            let is_empty = false;
+            // No pages in DB file or WAL -> empty database
+            let is_empty = self.db_file.size()? == 0
```
Comment (pereman2) [inline core/lib.rs:206]: if db size is > 0 && < 4096 maybe worth dropping an error

Comment (pereman2) [reply core/lib.rs:206]: if max_frame > 0 and !is_empty looks like an error too, database always starts with something before appending frames

File: core/storage/header_accessor.rs [hunk 9]
```diff
@@ -0,0 +1,161 @@
...
+            "Database is empty, header does not exist - page 1 should've been allocated before this".to_string(),
+        ));
+    }
+    let page = pager.read_page(DATABASE_HEADER_PAGE_ID)?;
+    while !page.is_loaded() || page.is_locked() {
+        // FIXME: LETS STOP DOING THESE SYNCHRONOUS IO HACKS
+        pager.io.run_once()?;
+    }
+    Ok(page)
+}
```
Comment (pereman2) [inline core/storage/header_accessor.rs:48]: Why should try to not do this sync I/O

File: core/storage/sqlite3_ondisk.rs [hunk 10]
```diff
@@ -247,7 +247,7 @@ impl Default for DatabaseHeader {
             min_embed_frac: 32,
             min_leaf_frac: 32,
             change_counter: 1,
-            database_size: 0,
+            database_size: 1,
```
Comment (el-yawd) [inline core/storage/sqlite3_ondisk.rs]: I think this is wrong, if we run `pragma page_count` without doing the first allocation it should return 0, with this change it would return 1.

File: core/storage/header_accessor.rs [hunk 11]
```diff
@@ -0,0 +1,161 @@
...
+/// - `pub fn get_<field_name>(pager: &Pager) -> Result<T>`
+/// - `pub fn set_<field_name>(pager: &Pager, value: T) -> Result<()>`
+///
+macro_rules! impl_header_field_accessor {
+    ($field_name:ident, $type:ty, $offset:expr $(, $ifzero:expr)?) => {
+        paste::paste! {
+            #[allow(dead_code)]
+            pub fn [<get_ $field_name>](pager: &Pager) -> Result<$type> {
+                if pager.is_empty.load(Ordering::SeqCst) {
+                    return Err(LimboError::InternalError(format!("Database is empty, header does not exist - page 1 should've been allocated before this")));
```
Comment (pereman2) [inline core/storage/header_accessor.rs:92]: This should probably return CursorResult<$type> because it should return I/O, this macro is quite scary because it hides so much complexity that is being misused

File: core/lib.rs (hunk 8 above)
Comment (jussisaurio) [reply core/lib.rs:206]: In limbo that is not true, we can append page 1 to wal and have zero-sized database. we don't have any code for special-casing page 1 to somehow always go to the main database file.

we do have `maybe_init_database_file` on `main`, but one of the points of this PR is to remove that so that we allocate the first page lazily like sqlite. 

the difference is sqlite has some logic to write page1 to the main DB file, but we don't, at least yet. so in our case we can have empty DB and nonempty WAL (which, from a functional standpoint, works, I guess)

File: core/storage/header_accessor.rs (hunk 9 above)
Comment (jussisaurio) [reply core/storage/header_accessor.rs:48]: this should eventually be a normal nonblocking pageload, right?

Comment (jussisaurio) [reply core/storage/header_accessor.rs:48]: oh, I guess you meant "should we make this async now". we could, it'll just make this PR a lot bigger

File: core/storage/header_accessor.rs (hunk 11 above)
Comment (jussisaurio) [reply core/storage/header_accessor.rs:92]: it will eventually return `CursorResult` once we make `get_header_page` nonblocking

File: core/storage/sqlite3_ondisk.rs (hunk 10 above)
Comment (jussisaurio) [reply core/storage/sqlite3_ondisk.rs]: In practice, the only place where we call `DatabaseHeader::default` is in `allocate_page1()`, and previously in this branch we immediately set the size to `1`, which `clippy` actually bitched about 😂 so I changed it.

File: core/storage/pager.rs (hunk 6 above)
Comment (jussisaurio) [reply core/storage/pager.rs:566]: i dunno about this mutex either, but the way we parse schema right now also dictates that we need to allocate page1 on a read transaction, e.g. `select * from sqlite_schema` on an empty db

File: core/storage/sqlite3_ondisk.rs (hunk 10 above)
Comment (jussisaurio) [reply core/storage/sqlite3_ondisk.rs]: BTW as it turns out this PR no longer fixes the `PRAGMA page_count` issue because we are now initializing page 1 on read transactions as well. The reason for doing that is that otherwise `SELECT * FROM sqlite_schema` doesn't work on an empty database because there is no page 1. Needs some other solution...

Comment (el-yawd) [reply core/storage/sqlite3_ondisk.rs]: Yeah, agree. I think we could left this other issue to another PR since this already is kinda big.

File: core/storage/pager.rs (hunk 6 above)
Comment (pereman2) [reply core/storage/pager.rs:566]: Okay anyways if we keep this for now we should change this lock usage to be something like `try_lock` and if it fails then it  means someones is allocating and must skip allocating *and wait for it to finish*
