### PR TITLE
Reconstruct WAL frame cache when WAL is opened

### LINKED ISSUE #1485: Tables and data visible in one connection are invisible to other connections
Tables and data successfully created, inserted, and retrieved in one connection are invisible to other connections for the same database file.

- Connection 1 creates a table (succeeds)
- Connection 1 inserts data (succeeds)
- Connection 1 can query and see its own data (succeeds)
- Other connections cannot even see the table exists

```
package main

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/tursodatabase/limbo"
)

func main() {
	// Create a fresh database file
	dbPath := "./limbo_bug_simple.db"
	os.Remove(dbPath)

	// Open connection
	db, err := sql.Open("sqlite3", dbPath)
	if err != nil {
		log.Fatalf("Failed to open database: %v", err)
	}
	defer db.Close()

	// Create a table and verify success
	log.Println("Step 1: Creating table")
	_, err = db.Exec(`CREATE TABLE test (id INTEGER PRIMARY KEY, value TEXT)`)
	if err != nil {
		log.Fatalf("CREATE TABLE failed: %v", err)
	}
	log.Println("CREATE TABLE reported success")

	// Insert data and verify success
	log.Println("Step 2: Inserting data")
	_, err = db.Exec(`INSERT INTO test (id, value) VALUES (1, 'test data')`)
	if err != nil {
		log.Fatalf("INSERT failed: %v", err)
	}
	log.Println("INSERT reported success")

	// Verify data in original connection
	log.Println("Step 3: Verifying data in original connection")
	var value string
	err = db.QueryRow("SELECT value FROM test WHERE id = 1").Scan(&value)
	if err != nil {
		log.Printf("Original connection SELECT error: %v", err)
	} else {
		log.Printf("Original connection can read data: '%s'", value)
	}

	// Create a second connection immediately
	log.Println("Step 4: Opening second connection")
	db2, err := sql.Open("sqlite3", dbPath)
	if err != nil {
		log.Fatalf("Failed to open second connection: %v", err)
	}
	defer db2.Close()

	// Try to read data from second connection
	log.Println("Step 5: Reading data from second connection")
	var count int
	err = db2.QueryRow("SELECT COUNT(*) FROM test").Scan(&count)
	if err != nil {
		log.Printf("Second connection query error: %v", err)
	} else {
		log.Printf("Second connection sees %d rows", count)
	}

	// Final verification
	log.Println("Step 6: Final verification with third connection")
	db3, err := sql.Open("sqlite3", dbPath)
	if err != nil {
		log.Fatalf("Failed to open third connection: %v", err)
	}
	defer db3.Close()

	// Try to read data from third connection
	err = db3.QueryRow("SELECT COUNT(*) FROM test").Scan(&count)
	if err != nil {
		log.Printf("Final verification error: %v", err)
	} else {
		log.Printf("Final verification sees %d rows", count)
	}

	// Check if the file exists and has content
	info, err := os.Stat(dbPath)
	if err != nil {
		log.Printf("Database file error: %v", err)
	} else {
		log.Printf("Database file exists, size: %d bytes", info.Size())
	}

	// Summary
	log.Println("\nSUMMARY:")
	log.Println("1. CREATE TABLE reported success")
	log.Println("2. INSERT INTO reported success")
	log.Println("3. Original connection can read its own data")
	log.Println("4. BUT other connections cannot even see the table exists")
}
```

Here's the output:

```
2025/05/14 18:04:42 Step 1: Creating table
2025/05/14 18:04:42 CREATE TABLE reported success
2025/05/14 18:04:42 Step 2: Inserting data
2025/05/14 18:04:42 INSERT reported success
2025/05/14 18:04:42 Step 3: Verifying data in original connection
2025/05/14 18:04:42 Original connection can read data: 'test data'
2025/05/14 18:04:42 Step 4: Opening second connection
2025/05/14 18:04:42 Step 5: Reading data from second connection
2025/05/14 18:04:42 Second connection query error: Parse error: Table test not found
2025/05/14 18:04:42 Step 6: Final verification with third connection
2025/05/14 18:04:42 Final verification error: Parse error: Table test not found
2025/05/14 18:04:42 Database file exists, size: 4096 bytes
2025/05/14 18:04:42 
SUMMARY:
2025/05/14 18:04:42 1. CREATE TABLE reported success
2025/05/14 18:04:42 2. INSERT INTO reported success
2025/05/14 18:04:42 3. Original connection can read its own data
2025/05/14 18:04:42 4. BUT other connections cannot even see the table exists
```

### LINKED ISSUE #1567: Database seems to be re-initialized whenever re-connecting to it
With this program
```rust
use limbo::Builder;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let db = Builder::new_local("database.db").build().await?;

    let conn = db.connect()?;
    // If you comment out the lines below you will get:
    // Error: SqlExecutionFailure("Parse error: Table test not found")
    // Despite the table being present before opening the connection.
    conn.execute("CREATE TABLE IF NOT EXISTS test(name text);", ()).await?;
    conn.execute("INSERT INTO test(name) values('Alice');", ()).await?;

    // We always only get the result added above, despite re-running the program
    // multiple times.
    let mut res = conn.query("SELECT name FROM test;", ()).await?;
    while let Some(row) = res.next().await.transpose() {
        if let Ok(row) = row {
            println!("{:?}", row.get_value(0)?);
        }
    }

    Ok(())
}
```

using these dependencies:
```toml
[dependencies]
limbo = "0.0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
```

I would have expected that when I re-run the program multiple times, I would get more and more rows returned over time. However this is not the case. I always only get one row.
I also only get one row after manually inserting a second row into the database:
Image
⬆ Running the program on this database also only yields: `Text("Alice")`.

Moreover, if these statements are commented out:
```rust
    //conn.execute("CREATE TABLE IF NOT EXISTS test(name text);", ()).await?;
    //conn.execute("INSERT INTO test(name) values('Alice');", ()).await?;
```
I get: `Error: SqlExecutionFailure("Parse error: Table test not found")`

I do not think this is #1485, because this program does work as expected:
```rust
use limbo::Builder;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let db = Builder::new_local("database.db").build().await?;

    let conn = db.connect()?;
    conn.execute("CREATE TABLE IF NOT EXISTS test(name text);", ()).await?;
    conn.execute("INSERT INTO test(name) values('Alice');", ()).await?;

    let mut res = conn.query("SELECT name FROM test;", ()).await?;
    while let Some(row) = res.next().await.transpose() {
        if let Ok(row) = row {
            println!("Conn: {:?}", row.get_value(0)?);
        }
    }

    let conn2 = db.connect()?;
    conn2.execute("INSERT INTO test(name) values('Bob');", ()).await?;

    let conn3 = db.connect()?;
    let mut res = conn3.query("SELECT name FROM test;", ()).await?;
    while let Some(row) = res.next().await.transpose() {
        if let Ok(row) = row {
            println!("Conn3: {:?}", row.get_value(0)?);
        }
    }

    Ok(())
}
```

Prints
```
Conn: Text("Alice")
Conn3: Text("Alice")
Conn3: Text("Bob")
```
as expected.

### Additional Information
Using _SQLite Studio_ I can see that the data is correctly stored in the database after running the program. For this reason it almost seems to me as if the database is reset whenever I run the program.

### PR DESCRIPTION
**Pull request by jussisaurio**
Fixes #1567 

Probably also fixes #1485 

Currently we are simply unable to read any WAL frames from disk once a fresh process w/ Limbo is opened, since we never try to read anything from disk unless we already have it in our in-memory frame cache.

This commit implements a crude way of reading entire WAL into memory as a single buffer and reconstructing the frame cache.

### CODE REVIEW

File: core/storage/wal.rs [hunk 1]
```diff
@@ -747,14 +756,20 @@ impl WalFileShared {
...
-            let wal_header = match sqlite3_ondisk::begin_read_wal_header(&file) {
-                Ok(header) => header,
-                Err(err) => return Err(LimboError::ParseError(err.to_string())),
-            };
-            tracing::info!("recover not implemented yet");
+            let wal_file_shared = sqlite3_ondisk::read_entire_wal_dumb(&file)?;
             // TODO: Return a completion instead.
-            io.run_once()?;
-            wal_header
+            let mut max_loops = 1000;
```
Comment (pereman2) [inline core/storage/wal.rs:761]: maybe 1000 is too little, let's use 100_000? In case we have a big wal to load

File: core/storage/sqlite3_ondisk.rs [hunk 2]
```diff
@@ -1354,37 +1357,171 @@ pub fn write_varint_to_vec(value: u64, payload: &mut Vec<u8>) {
...
+        }
+        let page_size = page_size_u32 as usize;
+
+        let mut current_offset = WAL_HEADER_SIZE;
+        let mut frame_idx = 1_u64;
+
+        let wfs_data = unsafe { &mut *wal_file_shared_for_completion.get() };
+
+        while current_offset + WAL_FRAME_HEADER_SIZE <= buf_slice.len()
+            && current_offset + WAL_FRAME_HEADER_SIZE + page_size <= buf_slice.len()
```
Comment (pereman2) [inline core/storage/sqlite3_ondisk.rs:1453]:
```suggestion
        while current_offset + WAL_FRAME_HEADER_SIZE + page_size <= buf_slice.len()
```
I guess this can be simplified to that.

**Review by pereman2 — APPROVED** [review]
