### PR TITLE
translate_condition_expr(): fix cases where 1. we jump on false and 2. either operand is NULL

### LINKED ISSUE #754: Condition expressions where an operand is NULL are broken
```
Limbo v0.0.13
Enter ".help" for usage hints.
limbo> select first_name from users where first_name = NULL limit 1;
Jamie
```

```
                Insn::Eq {
                    lhs,
                    rhs,
                    target_pc,
                } => {
                    assert!(target_pc.is_offset());
                    let lhs = *lhs;
                    let rhs = *rhs;
                    let target_pc = *target_pc;
                    match (&state.registers[lhs], &state.registers[rhs]) {
                        (_, OwnedValue::Null) | (OwnedValue::Null, _) => {
                            state.pc += 1;
                        }
                        _ => {
                            if state.registers[lhs] == state.registers[rhs] {
                                state.pc = target_pc.to_offset_int();
                            } else {
                                state.pc += 1;
                            }
                        }
                    }
                }
```

Looks like we just never jump if either is null for any of the comparison instructions 😂 

I guess this needs similar handling as `wrap_eval_jump_expr_zero_or_null()` but for condition expressions.

### PR DESCRIPTION
**Pull request by jussisaurio**
Change explanation is in the code comment for `Insn::Eq`:

```
        /// Jump if either of the operands is null. Used for "jump when false" logic.
        /// Eg. "SELECT * FROM users WHERE id = NULL" becomes:
        /// <JUMP TO NEXT ROW IF id != NULL>
        /// Without the jump_if_null flag it would not jump because the logical comparison "id != NULL" is never true.
        /// This flag indicates that if either is null we should still jump.
        jump_if_null: bool,      
```

Closes #754 

Excerpt from SQLite bytecode documentation for e.g. `Lt`:

> If the SQLITE_JUMPIFNULL bit of P5 is set and either reg(P1) or reg(P3) is NULL then the take the jump. If the SQLITE_JUMPIFNULL bit is clear then fall through if either operand is NULL.

I didn't want to start putting these flags into a bitmask so I just added a separate boolean. Probably for sqlite `EXPLAIN` compatibility we should, IF we want to be exactly compatible (which we aren't anyway atm)

### CODE REVIEW

File: core/translate/expr.rs [hunk 1]
```diff
@@ -23,13 +23,13 @@ fn emit_cond_jump(program: &mut ProgramBuilder, cond_meta: ConditionMetadata, re
         program.emit_insn(Insn::If {
             reg,
             target_pc: cond_meta.jump_target_when_true,
-            null_reg: reg,
+            jump_if_null: reg,
```
Comment (jussisaurio) [inline core/translate/expr.rs:26]: Note: i didn't change this here to reduce the scope but we are misusing `null_reg` or `jump_if_null` or whatever in places that had it already. This is not supposed to be read from a register but it's a literal boolean flag parameter.

Opinions on whether I fix this in the same PR or leave a FIXME somewhere?

`jump_if_null: bool` was _added_ to Eq,Ne,Lt,Le,Gt and Ge.

File: core/vdbe/mod.rs [hunk 2]
```diff
@@ -512,14 +512,19 @@ impl Program {
...
+                    jump_if_null,
                 } => {
                     assert!(target_pc.is_offset());
                     let lhs = *lhs;
                     let rhs = *rhs;
                     let target_pc = *target_pc;
                     match (&state.registers[lhs], &state.registers[rhs]) {
                         (_, OwnedValue::Null) | (OwnedValue::Null, _) => {
-                            state.pc += 1;
+                            if *jump_if_null {
```
Comment (psvri) [inline core/vdbe/mod.rs:523]: @jussisaurio 

Why not change ParrtialEq/PartialCmp of OwnedValue to return false when 2 values are null. And then lets remove the special handling in our code for nulls and if false we step counter by 1.
