### PR TITLE
Aggregation without group by produces incorrect results for scalars

### LINKED ISSUE #954: Aggregation without group by produces incorrect results for scalars
```
limbo> select id, count(1) from users;
NULL|10000
```

### PR DESCRIPTION
**Pull request by ihorandrianov**
Closes #954
Before:
Знімок екрана 2025-03-27 о 21 49 19

After:

Знімок екрана 2025-03-27 о 21 49 44

SQLite:

Знімок екрана 2025-03-27 о 21 50 04

### CODE REVIEW

**Comment by jussisaurio** [comment]
Hi, thanks! this fix needs to be a bit more general in my opinion - things like this still give incorrect results:

```
# notice id is not in the group by clause, but sqlite still returns the first id per group, whereas limbo returns NULL
select id, first_name, sum(age) from users group by first_name limit 1;
42|Aaron|2271
```

**Comment by ihorandrianov** [comment]
Ready for second review try. Also fixed order by elimination when group by is present like: 
```
select id, first_name, sum(age) from users group by first_name order by id limit 5;
```

**Comment by jussisaurio** [comment]
Hi @ihorandrianov can you please add at least TCL tests (*.test) that demonstrate the fix works?

File: core/translate/group_by.rs [hunk 1]
```diff
@@ -156,14 +163,22 @@ pub fn emit_group_by<'a>(
...
+
     // all group by columns and all arguments of agg functions are in the sorter.
     // the sort keys are the group by columns (the aggregation within groups is done based on how long the sort keys remain the same)
-    let sorter_column_count = group_by.exprs.len()
-        + plan
-            .aggregates
-            .iter()
-            .map(|agg| agg.args.len())
-            .sum::<usize>();
+    let sorter_column_count = non_aggregate_count + agg_args_count;
```
Comment (jussisaurio) [inline core/translate/group_by.rs:180]: The comment above should now say "all non-aggregate columns and all arguments of agg functions are in the sorter"

File: core/translate/group_by.rs [hunk 2]
```diff
@@ -296,7 +311,7 @@ pub fn emit_group_by<'a>(
     });
 
     // Read the group by columns for a finished group
-    for i in 0..group_by.exprs.len() {
+    for i in 0..non_aggregate_count {
```
Comment (jussisaurio) [inline core/translate/group_by.rs:314]: `// Read the non-aggregate columns for a finished group`

File: core/translate/group_by.rs [hunk 3]
```diff
@@ -363,6 +378,11 @@ pub fn emit_group_by<'a>(
         });
     }
 
+    let filtered_results = plan
+        .result_columns
+        .iter()
+        .filter(|rc| !rc.contains_aggregates)
+        .collect::<Vec<_>>();
```
Comment (jussisaurio) [inline core/translate/group_by.rs:385]: This should be called `non_aggregate_result_columns` and I don't think we need to `.collect()`

File: core/translate/group_by.rs [hunk 4]
```diff
@@ -373,6 +393,24 @@ pub fn emit_group_by<'a>(
             .expr_to_reg_cache
             .push((expr, reg_group_exprs_acc + i));
     }
+
+    // Offset for the next expressions after group_by
```
Comment (jussisaurio) [inline core/translate/group_by.rs:397]: `// Register offset for the non-aggregate expressions that are not part of GROUP BY`

File: core/translate/group_by.rs [hunk 5]
```diff
@@ -373,6 +393,24 @@ pub fn emit_group_by<'a>(
...
+    let mut offset = group_by.exprs.len();
+
+    for rc in filtered_results.iter() {
+        let expr = &rc.expr;
+
+        // skip cols that are already in group by
+        if !matches!(expr, ast::Expr::Column { .. })
```
Comment (jussisaurio) [inline core/translate/group_by.rs:404]: Why is this `!matches!(...)` here?

File: core/translate/emitter.rs [hunk 6]
```diff
@@ -63,6 +63,8 @@ pub struct TranslateCtx<'a> {
     pub label_main_loop_end: Option<BranchOffset>,
     // First register of the aggregation results
     pub reg_agg_start: Option<usize>,
+    // Register to track if we set non aggregate cols to first encountered row in non group by agg statement
+    pub reg_agg_flag: Option<usize>,
```
Comment (jussisaurio) [inline core/translate/emitter.rs:67]: Could this be called `reg_nonagg_emit_once_flag` for example?

File: core/translate/main_loop.rs [hunk 7]
```diff
@@ -599,6 +605,25 @@ fn emit_loop_source(
                     &t_ctx.resolver,
                 )?;
             }
+
+            if group_by.exprs.len() + aggregates.len() != plan.result_columns.len() {
```
Comment (jussisaurio) [inline core/translate/main_loop.rs:609]: `let has_extra_cols = group_by.exprs.len() + aggregates.len() != plan.result_columns.len()`
`if has_extra_cols { ... }`

File: core/translate/main_loop.rs [hunk 8]
```diff
@@ -599,6 +605,25 @@ fn emit_loop_source(
...
+                            program,
+                            Some(&plan.table_references),
+                            expr,
+                            key_reg,
+                            &t_ctx.resolver,
+                        )?;
+                    }
+                }
+            }
+            // Process non-aggregate result columns that aren't already in group_by
```
Comment (jussisaurio) [inline core/translate/main_loop.rs:625]: should this comment be above the last `if` statement and not below?

File: core/translate/main_loop.rs [hunk 9]
```diff
@@ -655,14 +680,31 @@ fn emit_loop_source(
...
-            for (i, rc) in plan.result_columns.iter().enumerate() {
-                if rc.contains_aggregates {
-                    // Do nothing, aggregates are computed above
-                    // if this result column is e.g. something like sum(x) + 1 or length(sum(x)), we do not want to translate that (+1) or length() yet,
-                    // it will be computed after the aggregations are finalized.
-                    continue;
-                }
-                let reg = start_reg + num_aggs + i;
+
+            let if_label = if let Some(flag) = t_ctx.reg_agg_flag {
```
Comment (jussisaurio) [inline core/translate/main_loop.rs:684]: `let label_emit_nonagg_only_once`?

File: core/translate/optimizer.rs [hunk 10]
```diff
@@ -100,6 +103,51 @@ fn query_is_already_ordered_by(
...
+    let o = plan.order_by.as_mut().unwrap();
+    let g = plan.group_by.as_mut().unwrap();
+
+    let mut insert_pos = 0;
+    let mut i = 0;
+
+    while i < o.len() {
+        let (key, order) = &o[i];
+
+        if matches!(order, Direction::Descending) {
```
Comment (jussisaurio) [inline core/translate/optimizer.rs:123]: please add comment

File: core/translate/optimizer.rs [hunk 11]
```diff
@@ -100,6 +103,51 @@ fn query_is_already_ordered_by(
...
+        }
+        if let Some(pos) = g
+            .exprs
+            .iter()
+            .position(|expr| exprs_are_equivalent(expr, key))
+        {
+            if pos != insert_pos {
+                let mut current_pos = pos;
+                while current_pos > insert_pos {
+                    g.exprs.swap(current_pos, current_pos - 1);
```
Comment (jussisaurio) [inline core/translate/optimizer.rs:135]: please add comment

File: core/translate/optimizer.rs [hunk 12]
```diff
@@ -108,6 +156,11 @@ fn eliminate_unnecessary_orderby(plan: &mut SelectPlan, schema: &Schema) -> Resu
         return Ok(());
     }
 
+    // if pk will be removed later
```
Comment (jussisaurio) [inline core/translate/optimizer.rs:159]: what does 'if pk' mean

File: core/translate/result_row.rs [hunk 13]
```diff
@@ -25,7 +25,9 @@ pub fn emit_select_result(
     }
 
     let start_reg = t_ctx.reg_result_cols_start.unwrap();
-    for (i, rc) in plan.result_columns.iter().enumerate() {
+    for (i, rc) in plan.result_columns.iter().enumerate().filter(|(_, rc)| {
+        t_ctx.reg_agg_flag.is_some() && rc.contains_aggregates || t_ctx.reg_agg_flag.is_none()
```
Comment (jussisaurio) [inline core/translate/result_row.rs:29]: what is happening here and why

File: core/translate/emitter.rs [hunk 14]
```diff
@@ -242,6 +247,14 @@ pub fn emit_query<'a>(
...
         });
     }
+    if !plan.aggregates.is_empty()
+        && plan.group_by.is_none()
+        && plan.result_columns.iter().any(|c| !c.contains_aggregates)
+    {
+        let flag = program.alloc_register();
+        program.emit_int(0, flag);
+        t_ctx.reg_nonagg_emit_once_flag = Some(flag);
+    }
```
Comment (pereman2) [inline core/translate/emitter.rs:257]: Can we have comment here about the behaviour? I know it's in the `reg_nonagg_emit_once_flag` definition but it could be good to know here too.

**Review by pereman2 — APPROVED** [review]
looks good for me, I cannot give better review than @jussisaurio

File: core/translate/group_by.rs [hunk 15]
```diff
@@ -146,25 +157,60 @@ pub fn emit_group_by<'a>(
...
+    // We have to know which group by expr present in resulting set
+    let group_by_expr_in_res_cols: Vec<bool> = group_by
+        .exprs
+        .iter()
+        .map(|expr| {
+            plan.result_columns
+                .iter()
+                .any(|e| exprs_are_equivalent(&e.expr, expr))
+        })
+        .collect();
```
Comment (jussisaurio) [inline core/translate/group_by.rs:187]: This section would probably be faster if we just computed `is_in_result` ad hoc:

```rust
    // Map GROUP BY columns that are in the result set to registers
    for i in 0..group_by.exprs.len() {
        let is_in_result = plan.result_columns.iter()... // etc
        if is_in_result {
            column_register_mapping.insert(i, next_reg);
            next_reg += 1;
        }
    }
    
    ...
    
    for (i, expr) in group_by.exprs.iter().enumerate() {
        let is_in_result = plan... // etc
        if is_in_result {
            if let Some(reg) = &column_register_mapping.get(&i) {
                t_ctx.resolver.expr_to_reg_cache.push((expr, **reg));
            }
        }
    }
```

File: core/translate/group_by.rs [hunk 16]
```diff
@@ -146,25 +157,60 @@ pub fn emit_group_by<'a>(
...
+
+    // Create a map from sorter column index to result register
+    // This helps track where each column from the sorter should be stored
+    let mut column_register_mapping = HashMap::new();
```
Comment (jussisaurio) [inline core/translate/group_by.rs:191]: this should have a capacity to avoid reallocation

```
HashMap::with_capacity(group_by_count + non_grouop_by_non_agg_column_count);
```

Also it would very likely be faster as a `Vec`

**Review by jussisaurio — APPROVED** [review]
Good stuff, I left some very minor nits
