### PR TITLE
Make cursor seek reentrant

### LINKED ISSUE #1617: Corrupt error when inserting two 1MB blobs in new database
```sql
$> limbo a.db                                                                                                                                                     Limbo v0.0.21
Enter ".help" for usage hints.
limbo> CREATE TABLE t(x UNIQUE);
limbo> INSERT INTO t VALUES (randomblob(1024 * 1024));
limbo> INSERT INTO t VALUES (randomblob(1024 * 1024));
thread 'main' panicked at core/storage/btree.rs:3831:22:
failed to read record: Corrupt("Invalid Blob value")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    1596772 IOT instruction (core dumped)  limbo a.db
```

### LINKED ISSUE #1625: Crash after page cache is full
Update with relatively big blob causes Limbo shell to crash

```sql
limbo> CREATE TABLE t(x);
limbo> INSERT INTO t VALUES (randomblob(4096));
limbo> UPDATE t SET x = randomblob(4096) WHERE rowid = 1;
thread 'main' panicked at core/storage/pager.rs:261:41:
called `Result::unwrap()` on an `Err` value: CacheFull
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    67095 IOT instruction (core dumped)  limbo a.db
```

The crash looks very suspicious as page cache should be very small (few pages) and this query shouldn't trigger it to overflow in any case.

### LINKED ISSUE #1628: DELETE Hang w/ table && primary key when (1 row, 1 col) with at least 999 bytes data
```sql
Limbo v0.0.21
Enter ".help" for usage hints.
limbo> create table t2(a primary key); insert into t2 values (randomblob(998)); delete from t2;
limbo> -- ok

Limbo v0.0.21
Enter ".help" for usage hints.
limbo> create table t2(a primary key); insert into t2 values (randomblob(998)); delete from t2;
limbo> -- ok

Limbo v0.0.21
Enter ".help" for usage hints.
limbo> create table t2(a primary key); insert into t2 values (randomblob(998)); delete from t2;
limbo> -- ok

Limbo v0.0.21
Enter ".help" for usage hints.
limbo> create table t2(a primary key); insert into t2 values (randomblob(999)); delete from t2;
-- hangs always

Limbo v0.0.21
Enter ".help" for usage hints.
limbo> create table t2(a primary key); insert into t2 values (randomblob(1000)); delete from t2;
-- hangs always
```

### PR DESCRIPTION
**Pull request by pedrocarlo**
Closes #1628.  Every function that calls `process_overflow_read` needs to be reentrant. I did not change it here, but it would include `get_prev_record` and `get_next_record`. Maybe `tablebtree_move_to` did not need to use the state machine, but I included it as a safeguard.

Edit: Closes #1625 . When I implemented `restore_context`, I forgot to add a `return_if_io` after calling it in `next` 🤦‍♂️

Edit: Closes #1617 . Just tested it and it also solves this bug.

### CODE REVIEW

**Comment by jussisaurio** [comment]
There should really be some tests for this (simulator or regular fuzzer) because although it makes #1628 work, it now makes #1625 behave like this:

```sql
limbo> CREATE TABLE t(x);
limbo> INSERT INTO t VALUES (randomblob(4096));
limbo> UPDATE t SET x = randomblob(4096) WHERE rowid = 1;
thread 'main' panicked at core/storage/sqlite3_ondisk.rs:626:9:
cell_get: idx out of bounds
```

**Comment by pedrocarlo** [comment]
Interesting. I will have to explore this second issue. However, I'm confident that the fix I did here should be correct. I think this fix just helped us catch a problem in the second issue haha

**Comment by jussisaurio** [comment]
> Interesting. I will have to explore this second issue. However, I'm confident that the fix I did here should be correct. 

Sure - but it would be great to have that encoded in a test

**Comment by pedrocarlo** [comment]
Yeah, of course. I just did not add it yet because I'm not at home yet haha.

**Comment by pedrocarlo** [comment]
While adding modifying some tests, I discovered some bugs in insert haha. Let me see if I can fix them.

**Comment by pedrocarlo** [comment]
@jussisaurio what an adventure! I think I solved it! After I added a `Delete` in the blob tests, I got myself into a rabbit hole of reentrance and page lock and loading that you have no idea. But now I think I returned to the surface with the prize. Well ... I think so at least. Let's see haha. Now, `find_cell` needed to become reentrant as well, and I had to isolate the state from `process_overflow_page` because some other functions depended on `self.state` together with `process_overflow_page`. So they were fighting for control of that variable. Now, we handle much better records that overflow and we can avoid some infinite loops I encountered while debugging. Now for the second issue, it still crashes with this fix, let me have a look at it better to see if it is related to #1628.

**Comment by pedrocarlo** [comment]
Found the issue and fixed it now

File: core/storage/btree.rs [hunk 1]
```diff
@@ -395,6 +406,202 @@ enum CursorValidState {
...
+        nearest_matching_cell: Option<usize>,
+        /// Indicates when we have not not found a value in leaf and now will look in the next/prev record.
+        /// This value is only used for indexbtree
+        not_found_leaf: bool,
+    },
+}
+
+// These functions below exist to avoid problems with the borrow checker
+impl CursorSeekState {
+    /// # Safety
```
Comment (jussisaurio) [inline core/storage/btree.rs]: Safety annotations are typically for `unsafe` code

File: core/storage/btree.rs [hunk 2]
```diff
@@ -395,6 +406,202 @@ enum CursorValidState {
...
+        };
+        *not_found_leaf
+    }
+}
+
+#[derive(Debug)]
+/// State used for seeking
+enum CursorMoveToState {
+    Start,
+    ContinueLoop,
```
Comment (jussisaurio) [inline core/storage/btree.rs:504]: The `ContinueLoop` state seems unnecessary since the only place where it's matched against is

```rust
            if matches!(
                self.move_to_state,
                CursorMoveToState::Start | CursorMoveToState::ContinueLoop
            )
```

and that matches `Start` too

File: core/storage/btree.rs [hunk 3]
```diff
@@ -3955,6 +4272,8 @@ impl BTreeCursor {
         // on the outer loop.
         self.set_null_flag(false);
         let cursor_has_record = return_if_io!(self.do_seek(key, op));
+        // Reset seek state
+        self.seek_state = CursorSeekState::Start;
```
Comment (jussisaurio) [inline core/storage/btree.rs:4269]: this probably needs to be reset in `prev` too then

**Review by jussisaurio — COMMENTED** [review]
I do wonder if we need some bigger refactoring of the btree if this problem really requires adding _four_ new state machines...

File: core/storage/btree.rs (hunk 2 above)
Comment (pedrocarlo) [reply core/storage/btree.rs:504]: I need to indicate that we are in the continue loop part. If I just set it up with `CursorMoveToState::Start` then on every Io we will trigger a `move_to_root` in `move_to` : 
```rust
if matches!(self.move_to_state, CursorMoveToState::Start) {
            self.move_to_root();
        }

```

**Comment by pedrocarlo** [comment]
I can try a refactor if you want. Just not sure the best way to make these functions reentrant without state machines.

**Comment by pedrocarlo** [comment]
Also Closes https://github.com/tursodatabase/limbo/issues/1617 . Just tested it and it also solves this bug.
