### PR TITLE
Fix `SELECT 0.0 = 0` returning false

### LINKED ISSUE #1155: `SELECT 0.0 = 0` incorrectly returns false
The current derived `PartialEq` trait doesn't handle this case, the two variants of an `enum` are always considered distinct. We should manually implement that trait to handle the edge case.

https://github.com/tursodatabase/limbo/blob/669317c11e24b56ab256d88c81161c9e69252ee8/core/types.rs#L64

Found while fuzzing in #1116. (`left` is sqlite)

```
thread '<unnamed>' panicked at fuzz_targets/expression.rs:209:5:
assertion `left == right` failed: with expression Output { query: "(?) = (?)", parameters: [Real(0.0), Integer(0)], depth: 1 }
  left: Integer(1)
 right: Integer(0)
```

### PR DESCRIPTION
**Pull request by lgualtieri75**
Fixes #1155

### CODE REVIEW

File: core/types.rs [hunk 1]
```diff
@@ -249,6 +249,45 @@ impl AggContext {
...
+            (Self::Text(_) | Self::Blob(_), Self::Integer(_) | Self::Float(_)) => false,
+            (Self::Text(text_left), Self::Text(text_right)) => {
+                text_left.value.eq(&text_right.value)
+            }
+            // Text vs Blob
+            // Blob <> Text in sqlite
+            //  (Self::Text(text_left), Self::Blob(blob_right)) =>
+            //                 text_left.as_str().to_string().as_bytes().to_vec() == blob_right.to_vec(),
+            //  (Self::Blob(blob_left), Self::Text(text_right)) =>
+            //     blob_left.to_vec() == text_right.as_str().to_string().as_bytes().to_vec(),
```
Comment (penberg) [inline core/types.rs:274]: Please drop commented out code.

File: core/types.rs [hunk 2]
```diff
@@ -249,6 +249,45 @@ impl AggContext {
...
+            (Self::Blob(blob_left), Self::Blob(blob_right)) => blob_left.eq(blob_right),
+            (Self::Null, Self::Null) => true,
+            // (Self::Null, _) => ,
+            // (_, Self::Null) => _,
```
Comment (penberg) [inline core/types.rs:278]: Ditto

**Comment by lgualtieri75** [comment]
done
